FROM golang:1.24-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# COPY configs/.env configs/.env
COPY configs/ ./configs/

COPY internal/domain/services/pdfgen/background.jpg /app/internal/domain/services/pdfgen/background.jpg

WORKDIR /app/cmd/app
RUN go build -o main .

EXPOSE 8080
CMD ["./main"]